Bad username

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -313,6 +313,93 @@ test-docker-build-ecr-1:
 test-docker-build-ecr-2:
   # This is part 2 of a two-part test, and must follow after test-docker-build-ecr-1
   # Test that we can pull the image that the preceding pipeline created in Amazon ECR, start it using internal/docker-run, and connect to it
+  # 
+  # This pipeline requires the following environment variables to be set:
+  #   AWS_REGION (e.g. us-east-1, us-east-2 or whatever)
+  #   AWS_ACCESS_KEY_ID
+  #   AWS_SECRET_ACCESS_KEY
+  #   ECR_REGISTRY (https://<aws_account_id>.dkr.ecr.<region>.amazonaws.com)
+  #   PAGERDUTY_SERVICE_KEY, PAGERDUTY_NOTIFY_ON, PAGERDUTY_BRANCH 
+  # Optional environment variables
+  #   PROD_OR_STAGING - set to a string to avoid repository name clashes between concurrent builds on prod and staging 
+  box: python
+  steps:
+    - script:
+        name: Get the a unique id for the run, common to all pipelines in the workflow
+        code: |
+          export BUILDID=`cat /pipeline/source/build-id`
+          echo BUILDID=$BUILDID
+          echo Copy build-id to /pipeline/output for any subsequent pipeline to use
+          cp /pipeline/source/build-id /pipeline/output            
+    - script:
+        name: Install AWS CLI
+        code: |
+          curl -O https://bootstrap.pypa.io/get-pip.py
+          python get-pip.py --user
+          export PATH=~/.local/bin:$PATH    
+          pip install awscli --upgrade --user
+          aws --version
+    - script:
+        name: Configure AWS CLI using AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
+        code: |
+          # The aws configure command prompts for (1) the access key id (2) the secret access key (3) the default region and (4) the default output format
+          # Note that we respond to question (4) with an empty line
+          aws configure <<!
+          $AWS_ACCESS_KEY_ID
+          $AWS_SECRET_ACCESS_KEY
+          $AWS_REGION
+
+          !
+    - script:
+        name: Construct repository name 
+        code: |
+          # Note that we convert PROD_OR_STAGING to lower case
+          export REPOSITORY_NAME=wercker-test-test-docker-build-ecr${PROD_OR_STAGING,,}
+          echo REPOSITORY_NAME=$REPOSITORY_NAME
+    - script:
+        name: Generate ECR authorization token (valid for registry for 12 hours)
+        code: |          
+          export ECR_USERNAME=AWS
+          export ECR_PASSWORD=`aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d | cut -d: -f2`
+    - internal/docker-run:
+        image: $ECR_REGISTRY/$REPOSITORY_NAME:latest
+        username: xx$ECR_USERNAME 
+        password: $ECR_PASSWORD 
+        name: myTestContainer
+    - script: 
+        name: Wait for container to start 
+        code: | 
+          until $(curl --output /dev/null --silent --head --fail http://myTestContainer:5000); do printf '.'; sleep 5; done        
+    - script: 
+        name: Test the container that we started using docker-run
+        code: |
+            if curlOutput=`curl -s myTestContainer:5000`; then 
+                export expected="Hello World!! $BUILDID"
+                if [ "$curlOutput" == "$expected" ]; then
+                    echo "Test passed: container gave expected response: " $expected
+                else
+                    echo "Test failed: container gave unexpected response: " $curlOutput
+                    echo "The expected response was: " $expected
+                    exit 1
+                fi   
+            else 
+                echo "Test failed: container did not respond"
+                exit 1
+            fi      
+    - internal/docker-kill:
+        name: myTestContainer  
+    - script:
+        name: Delete repository  
+        code: aws ecr delete-repository --repository-name $REPOSITORY_NAME --force  
+  after-steps:
+    - nigeldeakin/pagerduty-notifier:
+        service-key: $PAGERDUTY_SERVICE_KEY
+        notify-on: $PAGERDUTY_NOTIFY_ON
+        branch: $PAGERDUTY_BRANCH   
+
+test-docker-build-ecr-3:
+  # This is part 3 of a two-part test, and must follow after test-docker-build-ecr-1
+  # Test that we can pull the image that the preceding pipeline created in Amazon ECR, start it using internal/docker-run, and connect to it
   # This pipeline requires the following environment variables to be set:
   #   AWS_REGION (e.g. us-east-1, us-east-2 or whatever)
   #   AWS_ACCESS_KEY_ID
@@ -389,12 +476,7 @@ test-docker-build-ecr-2:
         name: myTestContainer  
     - script:
         name: Delete repository  
-        code: aws ecr delete-repository --repository-name $REPOSITORY_NAME --force  
-  after-steps:
-    - nigeldeakin/pagerduty-notifier:
-        service-key: $PAGERDUTY_SERVICE_KEY
-        notify-on: $PAGERDUTY_NOTIFY_ON
-        branch: $PAGERDUTY_BRANCH   
+        code: aws ecr delete-repository --repository-name $REPOSITORY_NAME --force          
 
 test-docker-build-ocir-1:
   # This is part 1 of a two-part test, and should be followed by test-docker-build-ocir-2
